FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    git build-essential zlib1g-dev libsqlite3-dev wget ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone https://github.com/felt/tippecanoe.git
WORKDIR /opt/tippecanoe
RUN make -j4 && make install

WORKDIR /data
ENTRYPOINT ["tippecanoe"]
