tile_buffer = 16

[webserver]
port = ":8080"

[cache]
type = "redis"
uri = "redis://geo-redis:6379/0"
max_zoom = 18

[[providers]]
name = "postgis"
type = "postgis"
uri = "postgres://postgres:Egor150101@host.docker.internal:5432/osm?sslmode=disable&pool_max_conns=10"
srid = 3857

  [[providers.layers]]
  name = "roads"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  geometry_type = "LineString"
  sql = """
    SELECT
      osm_id,
      ST_AsBinary(way) AS geom
    FROM public.planet_osm_line
    WHERE highway IS NOT NULL
      AND way && !BBOX!
  """

  [[providers.layers]]
  name = "water"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  geometry_type = "Polygon"
  sql = """
    SELECT
      osm_id,
      ST_AsBinary(way) AS geom
    FROM public.planet_osm_polygon
    WHERE water IS NOT NULL
      AND way && !BBOX!
  """

  [[providers.layers]]
  name = "buildings"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  geometry_type = "Polygon"
  sql = """
    SELECT
      osm_id,
      ST_AsBinary(way) AS geom
    FROM public.planet_osm_polygon
    WHERE building IS NOT NULL
      AND way && !BBOX!
  """

  [[providers.layers]]
  name = "places"
  geometry_fieldname = "geom"
  id_fieldname = "osm_id"
  geometry_type = "Point"
  sql = """
    SELECT
      osm_id,
      ST_AsBinary(way) AS geom
    FROM public.planet_osm_point
    WHERE place IS NOT NULL
      AND way && !BBOX!
  """

[[maps]]
name = "map"

  [[maps.layers]]
  provider_layer = "postgis.roads"
  min_zoom = 8
  max_zoom = 22

  [[maps.layers]]
  provider_layer = "postgis.water"
  min_zoom = 5
  max_zoom = 22

  [[maps.layers]]
  provider_layer = "postgis.buildings"
  min_zoom = 14
  max_zoom = 22

  [[maps.layers]]
  provider_layer = "postgis.places"
  min_zoom = 10
  max_zoom = 22